const Assets =[
    {
        id: '1',
        title: 'Marketing Manager',
        Department: 'Marketing',
        Location: 'Chennai',
        Responsibility:'Analyse information to identify new markets',
        Qualification: '2 years experience in the marketing field',
        Category: 'Free',
    },
    {
        id: '2',
        title: 'Marketing Manager',
        Department: 'Marketing',
        Location: 'Mumbai',
        Responsibility:'Analyse information to identify new markets',
        Qualification: '2 years experience in the marketing field',
        Category: 'Free',
    },
    {
        id: '3',
        title: 'Marketing Manager',
        Department: 'Marketing',
        Location: 'Coimbatore',
        Responsibility:'Analyse information to identify new markets',
        Qualification: '2 years experience in the marketing field',
        Category: 'Free',
    },
    {
        id: '4',
        title: 'Marketing Manager',
        Department: 'software',
        Location: 'Chennai',
        Responsibility:'Analyse information to identify new markets',
        Qualification: '2 years experience in the marketing field',
        Category: 'Free',
    },
    {
        id: '5',
        title: 'Marketing Manager',
        Department: 'Marketing',
        Location: 'Chennai',
        Responsibility:'Analyse information to identify new markets',
        Qualification: 'No experience required',
        Category: 'Free',
    },
    {
    
            id: '6',
            title: 'Marketing Manager',
            Department: 'Marketing',
            Location: 'Chennai',
            Responsibility:'Analyse information to identify new markets',
            Qualification: 'No experience required',
            Category: 'Premium',
        
    },
    {
        id: '7',
        title: 'Marketing Manager',
        Department: 'Marketing',
        Location: 'Chennai',
        Responsibility:'Analyse information to identify new markets',
        Qualification: 'No experience required',
        Category: 'Premium',
    },{
        id: '8',
        title: 'Marketing Manager',
        Department: 'Marketing',
        Location: 'Chennai',
        Responsibility:'Analyse information to identify new markets',
        Qualification: 'No experience required',
        Category: 'Premium',
    },{
        id: '9',
        title: 'Marketing Manager',
        Department: 'Marketing',
        Location: 'Chennai',
        Responsibility:'Analyse information to identify new markets',
        Qualification: 'No experience required',
        Category: 'Premium',
    },{
        id: '10',
        title: 'Marketing Manager',
        Department: 'Marketing',
        Location: 'Chennai',
        Responsibility:'Analyse information to identify new markets',
        Qualification: 'No experience required',
        Category: 'Premium',
    },
];

export default Assets